#   -----------------   WindowsUtility Constants     -----------------
MAIN_BACKGROUND_COLOR = '#e5e5e5'

FONT_FAMILY = 'arial'

H1_FONT_SIZE = '36px'
H1_FONT_WEIGHT = 'bold'
H1_PADDING = '5px 0 5px 0'
H1_COLOR = 'black'
H1_BACKGROUND_COLOR = '#b8bfbf'

H2_FONT_SIZE = '28px'
H2_FONT_WEIGHT = 'bold'
H2_COLOR = '#32CD32'

P_FONT_SIZE = '18px'
P_COLOR = '#808080'

INPUT_BORDER = '2px solid black'
INPUT_BACKGROUND_COLOR = '#c5c6c7'
INPUT_HOVER_BACKGROUND_COLOR = '#b3f1ff'
INPUT_HOVER_TEXT_COLOR = '#005b6f'
INPUT_BORDER_RADIUS = '5px'
INPUT_WEIGHT = 'bold'

BUTTON_BORDER = '2px solid white'
BUTTON_BORDER_RADIUS = '5px'
BUTTON_COLOR_ACCEPT = '#ab22ff'
BUTTON_COLOR_HOVER_ACCEPT = '#851dc4'
BUTTON_COLOR_REFUSE = '#ff035e'
BUTTON_COLOR_HOVER_REFUSE = '#c60047'
BUTTON_WEIGHT = 'bold'
